#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash syn_flow/common/run_pt.sh <design>

Required environment exported by wrapper:
  TOP_MODULE
  TB_FILE
  TB_TOP

Optional wrapper environment:
  TB_SUPPORT_FILES   colon-separated helper source files
  PT_PREPARE_CMD     command run before VCS
  INPUT_VEC_FILE     joint vector input file
  GOLDEN_VEC_FILE    joint golden output file
  OUTPUT_FILE        waveform/text dump generated by TB
EOF
}

quote_cmd() {
  printf '%q ' "$@"
}

run_with_optional_bsub() {
  local log_file="$1"
  shift

  local cmd_str
  cmd_str="$(quote_cmd "$@")"

  if [[ -n "${BSUB_PREFIX// }" ]]; then
    eval "$BSUB_PREFIX $cmd_str" 2>&1 | tee "$log_file"
  else
    eval "$cmd_str" 2>&1 | tee "$log_file"
  fi
}

append_split_paths() {
  local raw="$1"
  local -n out_ref="$2"
  local item
  IFS=':' read -r -a __items <<<"$raw"
  for item in "${__items[@]}"; do
    [[ -z "$item" ]] && continue
    out_ref+=("$item")
  done
}

if [[ $# -ne 1 ]]; then
  usage
  exit 2
fi

DESIGN="$1"

FLOW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_DIR="$(cd "$FLOW_DIR/.." && pwd)"
DESIGN_DIR="$FLOW_DIR/designs/$DESIGN"
CONFIG_FILE="$DESIGN_DIR/config.tcl"
RUN_ROOT="$FLOW_DIR/runs/$DESIGN"

if [[ ! -d "$RUN_ROOT" ]]; then
  echo "[PT][ERR] run directory not found: $RUN_ROOT"
  exit 2
fi
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "[PT][ERR] missing design config: $CONFIG_FILE"
  exit 2
fi
if [[ -z "${TOP_MODULE:-}" || -z "${TB_FILE:-}" || -z "${TB_TOP:-}" ]]; then
  echo "[PT][ERR] wrapper must export TOP_MODULE, TB_FILE and TB_TOP"
  exit 2
fi

: "${BSUB_PREFIX:=bsub -Is -XF}"
: "${VCS_BIN:=vcs}"
: "${PT_SHELL_BIN:=/tools/synopsys/prime/V-2023.12/bin/pt_shell}"
: "${TARGET_LIB:=/dx_s702/vol_s702a0_dev/tsmc22ull/sylincom/STDCELL/tcbn22ullbwp7t35p140_110b/TSMCHOME/digital/Front_End/timing_power_noise/CCS/tcbn22ullbwp7t35p140_110b/tcbn22ullbwp7t35p140ssg0p72vm40c_ccs.db}"
: "${LINK_LIB:=$TARGET_LIB}"
: "${SEARCH_PATHS:=}"
: "${SIM_LIB_FILES:=}"
: "${PYTHON_BIN:=python3}"

if [[ -z "$SIM_LIB_FILES" && "$TARGET_LIB" == "$ROOT_DIR/lib/gscl45nm/gscl45nm.lib" ]]; then
  SIM_LIB_FILES="$ROOT_DIR/lib/gscl45nm/gscl45nm.v"
fi

if [[ -z "$SIM_LIB_FILES" ]]; then
  echo "[PT][ERR] SIM_LIB_FILES is required for gate-level simulation."
  echo "[PT][ERR] Example: export SIM_LIB_FILES=/abs/path/stdcells.v"
  exit 2
fi

NETLIST_FILE="$RUN_ROOT/mapped/${TOP_MODULE}-mapped.v"
MAPPED_SDC="$RUN_ROOT/mapped/${TOP_MODULE}-mapped.sdc"
SAIF_FILE="$RUN_ROOT/power/${TOP_MODULE}.saif"
POWER_BUILD_DIR="$RUN_ROOT/power/build"
COMPILE_LOG="$RUN_ROOT/logs/vcs_compile.log"
SIM_LOG="$RUN_ROOT/logs/vcs_sim.log"
PT_LOG="$RUN_ROOT/logs/pt_shell.log"
SIM_OUT="$POWER_BUILD_DIR/${TB_TOP}.simv"

mkdir -p "$POWER_BUILD_DIR" "$RUN_ROOT/logs" "$RUN_ROOT/power"

if [[ ! -f "$NETLIST_FILE" ]]; then
  echo "[PT][ERR] mapped netlist missing: $NETLIST_FILE"
  exit 2
fi
if [[ ! -f "$MAPPED_SDC" ]]; then
  echo "[PT][ERR] mapped SDC missing: $MAPPED_SDC"
  exit 2
fi
if [[ ! -f "$TB_FILE" ]]; then
  echo "[PT][ERR] TB file missing: $TB_FILE"
  exit 2
fi

if [[ -n "${PT_PREPARE_CMD:-}" ]]; then
  echo "[PT] running prepare command"
  eval "$PT_PREPARE_CMD"
fi

declare -a vcs_sources
append_split_paths "$SIM_LIB_FILES" vcs_sources
append_split_paths "${TB_SUPPORT_FILES:-}" vcs_sources
vcs_sources+=("$NETLIST_FILE" "$TB_FILE")

declare -a vcs_cmd=(
  "$VCS_BIN"
  -full64
  -sverilog
  -timescale=1ns/1ps
  +define+SYNOPSYS_SAIF
  -top "$TB_TOP"
  -o "$SIM_OUT"
)
vcs_cmd+=("${vcs_sources[@]}")

declare -a sim_args
sim_args+=("+SAIF_FILE=$SAIF_FILE")
if [[ -n "${INPUT_VEC_FILE:-}" ]]; then
  sim_args+=("+INPUT_VEC=$INPUT_VEC_FILE")
fi
if [[ -n "${GOLDEN_VEC_FILE:-}" ]]; then
  sim_args+=("+GOLDEN_VEC=$GOLDEN_VEC_FILE")
fi
if [[ -n "${OUTPUT_FILE:-}" ]]; then
  sim_args+=("+OUTPUT_FILE=$OUTPUT_FILE")
fi

echo "[PT] design=$DESIGN"
echo "[PT] run_root=$RUN_ROOT"
echo "[PT] saif=$SAIF_FILE"

(
  cd "$RUN_ROOT/power"
  run_with_optional_bsub "$COMPILE_LOG" "${vcs_cmd[@]}"
)

(
  cd "$RUN_ROOT/power"
  run_with_optional_bsub "$SIM_LOG" "$SIM_OUT" "${sim_args[@]}"
)

if ! grep -q "\[.*PASS\]" "$SIM_LOG"; then
  echo "[PT][ERR] simulation log does not contain PASS marker: $SIM_LOG"
  exit 1
fi

if [[ ! -s "$SAIF_FILE" ]]; then
  echo "[PT][ERR] SAIF file missing or empty: $SAIF_FILE"
  exit 1
fi

export REPO_ROOT="$ROOT_DIR"
export DESIGN_CONFIG="$CONFIG_FILE"
export RUN_ROOT
export TARGET_LIB
export LINK_LIB
export SEARCH_PATHS
export SAIF_FILE

PT_TCL="$FLOW_DIR/common/pt_main.tcl"
(
  cd "$RUN_ROOT/power"
  run_with_optional_bsub "$PT_LOG" "$PT_SHELL_BIN" -file "$PT_TCL"
)

"$PYTHON_BIN" "$ROOT_DIR/psrc/export_syn_reports.py" \
  --mode pt \
  --repo-root "$ROOT_DIR" \
  --run-root "$RUN_ROOT" \
  --design "$DESIGN" \
  --clock-ns "${CLOCK_NS:-}" \
  --config "$CONFIG_FILE" \
  --top-module "$TOP_MODULE"

echo "[PT][OK] finished: $RUN_ROOT"
