function [tx_lin, backend_meta, params] = applyLinearizationBackend(tx_sum, params)
    if ~isfield(params, 'experiment') || ~isfield(params.experiment, 'active_case') ...
            || isempty(fieldnames(params.experiment.active_case))
        tx_lin = tx_sum;
        backend_meta = struct('backend_name', 'passthrough', 'status', 'ok');
        return;
    end

    case_cfg = params.experiment.active_case;
    exchange_dir = fullfile( ...
        params.linearization.exchange_root, ...
        char(case_cfg.case_id), ...
        sprintf('iter_%03d', params.info.IterNum));

    if ~exist(exchange_dir, 'dir')
        mkdir(exchange_dir);
    end

    input_csv = fullfile(exchange_dir, 'input_signal.csv');
    input_meta = fullfile(exchange_dir, 'input_meta.json');
    output_csv = fullfile(exchange_dir, 'output_signal.csv');
    output_meta = fullfile(exchange_dir, 'output_meta.json');

    writeComplexCsv(input_csv, tx_sum);
    writeJsonFile(input_meta, buildBackendPayload(tx_sum, params, case_cfg));

    cmd = sprintf('%s %s --input-csv %s --input-meta %s --output-csv %s --output-meta %s', ...
        quoteShellArg(char(params.linearization.python_cmd)), ...
        quoteShellArg(char(params.linearization.backend_entry)), ...
        quoteShellArg(input_csv), ...
        quoteShellArg(input_meta), ...
        quoteShellArg(output_csv), ...
        quoteShellArg(output_meta));

    [status, cmdout] = system(cmd);
    if status ~= 0
        error('Linearization backend failed for case %s (iter %d).\nCommand: %s\nOutput:\n%s', ...
            params.info.CaseId, params.info.IterNum, cmd, cmdout);
    end

    tx_lin = readComplexCsv(output_csv);
    if numel(tx_lin) ~= numel(tx_sum)
        error('Linearization backend output length mismatch for case %s: got %d expect %d.', ...
            params.info.CaseId, numel(tx_lin), numel(tx_sum));
    end
    tx_lin = reshape(tx_lin, size(tx_sum));

    backend_meta = readJsonFile(output_meta);
    params.linearization.last_exchange_dir = exchange_dir;
    params.linearization.last_backend_stdout = string(cmdout);
end


function payload = buildBackendPayload(tx_sum, params, case_cfg)
    volterra_pairs = [real(params.linearization.volterra_coeffs(:)), imag(params.linearization.volterra_coeffs(:))];
    payload = struct( ...
        'case_id', char(case_cfg.case_id), ...
        'iter_idx', params.info.IterNum, ...
        'backend_mode', char(case_cfg.backend_mode), ...
        'filter_method', char(case_cfg.filter_method), ...
        'cfr_mode', char(case_cfg.cfr_mode), ...
        'dpd_mode', char(case_cfg.dpd_mode), ...
        'randseed', params.info.randseed, ...
        'signal_length', numel(tx_sum), ...
        'Fs_total', params.rf.Fs_total, ...
        'TargetPeakAmp', params.PA.TargetPeakAmp, ...
        'linearization', struct( ...
            'hc_clip_max', params.linearization.hc_clip_max, ...
            'dpd_iterations', params.linearization.dpd_iterations, ...
            'dpd_step', params.linearization.dpd_step, ...
            'volterra_coeffs_real_imag', volterra_pairs, ...
            'model_manifest', params.linearization.model_manifest, ...
            'model_bin_dir', params.linearization.model_bin_dir));
end


function quoted = quoteShellArg(value)
    value = string(value);
    if ispc
        quoted = sprintf('"%s"', replace(value, '"', '""'));
    else
        value = replace(value, "'", "'\"'\"'");
        quoted = sprintf('''%s''', value);
    end
end
