function case_configs = buildDefaultBerExperimentCases()
    case_configs = [ ...
        makeCase("migo_no_cfr_no_dpd", "MIGO", "none", "none", "passthrough"), ...
        makeCase("migo_hc_no_dpd", "MIGO", "hc", "none", "hc_only"), ...
        makeCase("migo_no_cfr_dpd", "MIGO", "none", "dpd", "dpd_only"), ...
        makeCase("migo_no_cfr_volterra", "MIGO", "none", "volterra", "volterra_only"), ...
        makeCase("migo_hc_volterra", "MIGO", "hc", "volterra", "hc_plus_volterra"), ...
        makeCase("migo_joint_cfr_dpd", "MIGO", "joint", "joint", "joint_cfr_dpd"), ...
        makeCase("wls_joint_cfr_dpd", "WLS", "joint", "joint", "joint_cfr_dpd"), ...
        makeCase("swls_joint_cfr_dpd", "SWLS", "joint", "joint", "joint_cfr_dpd") ...
    ];
end


function cfg = makeCase(case_id, filter_method, cfr_mode, dpd_mode, backend_mode)
    cfg = struct( ...
        'case_id', string(case_id), ...
        'filter_method', string(filter_method), ...
        'cfr_mode', string(cfr_mode), ...
        'dpd_mode', string(dpd_mode), ...
        'backend_mode', string(backend_mode));
end
